### ISSUE TITLE
Conflicting file extensions

### ISSUE THREAD

**Issue by ramidzkh** [SebastiaanYN/SourceBin#2]
# Brief
When loading a bin in a certain language that has other languages using the same file extension, the first (alphabetically) language is chosen. 

## Reproduction
1. Create a bin in `Rust`
2. Save it
3. Go to the link
4. See the language to be `RenderScript`

## Expected behaviour
The saved bin should be highlighted in rust

## Device
Ubuntu 18.04 LTS, Chrome 72

**Comment by SebastiaanYN** [comment]
Thanks for reporting, this has been fixed in 02d028e
