### ISSUE TITLE
Newly-saved bins don't behave properly

### ISSUE THREAD

**Issue by MyriaCore** [SebastiaanYN/SourceBin#3]
**Describe the bug**
It is impossible to re-save a newly-saved bin. Hovering over the save button turns your cursor into the `not-allowed` icon. Pressing `ctrl+s` does nothing. In order to re-save, the user must either reload the page, or copy/paste the link back into the browser.

**To Reproduce**
1. Go to the site and create a new bin
2. Save it
3. Try to edit immediately after saving

**Expected behavior**
Should behave as a new, unsaved bin.

**Comment by SebastiaanYN** [comment]
This is fixed since #5
